# -*- coding: utf-8 -*-
"""Data_visualization.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1veiRYY925lfKf7pOSPYAFZcQ8kpmk33M
"""

import matplotlib.pyplot as plt

import pandas as pd
import numpy as np
mtcars=pd.read_csv('/content/mtcars.csv')

mtcars.head()

mtcars.columns
mtcars.shape

pd.crosstab(mtcars.gear,mtcars.cyl).plot(kind="bar")

import seaborn as sns

tips=sns.load_dataset("tips")

sns.stripplot(y='tip', data =tips ,jitter=False)
plt.ylabel('tip ($)')
plt.show()

sns.stripplot(x='day',y='tip',data=tips)
plt.ylabel('tip ($)')
plt.show()

plt.violinplot(mtcars["mpg"])

sns.swarmplot(x='day',y='tip',data =tips,hue='sex')
plt.ylabel('tip($')
plt.show()

sns.jointplot(x='total_bill',y='tip',data =tips)
plt.show()

sns.jointplot(x='total_bill',y='tip',data =tips,kind="kde")
plt.show()

data=pd.read_csv("/content/train.csv")

data.groupby('Survived')['PassengerId'].count()

f, ax =plt.subplots(figsize=(10,8))
sns.barplot(x='Sex',y='Survived',data=data)

sns.barplot(x="Pclass",y="Survived",hue="Sex",data=data)

sns.barplot(x="SibSp",y="Survived",data=data)

survived=data.loc[data['Survived']==1,"Age"].dropna()
sns.distplot(survived)
plt.title("Survived")

not_survived=data.loc[data['Survived']==0,"Age"].dropna()
sns.distplot(not_survived)
plt.title("Not Survived")

grid=sns.FacetGrid(data,col='Survived',row='Pclass',size=2.4,aspect=1.5)
grid.map(plt.hist,'Age',alpha=.5,bins=20)
grid.add_legend()

figbi,axesbi=plt.subplots(2,4,figsize=(16,10))
data.groupby('Pclass')['Survived'].mean().plot(kind='barh',ax=axesbi[0,0],xlim=[0,1])
data.groupby('SibSp')['Survived'].mean().plot(kind='barh',ax=axesbi[0,1],xlim=[0,1])
data.groupby('Parch')['Survived'].mean().plot(kind='barh',ax=axesbi[0,2],xlim=[0,1])
data.groupby('Sex')['Survived'].mean().plot(kind='barh',ax=axesbi[0,3],xlim=[0,1])
data.groupby('Embarked')['Survived'].mean().plot(kind='barh',ax=axesbi[1,0],xlim=[0,1])

sns.boxplot(x='Survived',y='Age',data=data,ax=axesbi[1,1])
sns.boxplot(x='Survived',y='Fare',data=data,ax=axesbi[1,2])

import pandas as pd
import seaborn as sns